# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rosary
      MYSQL_USER: gomes
      MYSQL_PASSWORD: rosary

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
