// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrareProMe.Infrastructure.Database;

namespace OrareProMe.Migrations
{
    [DbContext(typeof(MysqlContext))]
    partial class MysqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("OrareProMe.Domain.Intention", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Intentions");
                });

            modelBuilder.Entity("OrareProMe.Domain.Prayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<long?>("RosaryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("RosaryId");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("OrareProMe.Domain.Rosary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<long?>("IntentionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("IntentionId");

                    b.ToTable("Rosaries");
                });

            modelBuilder.Entity("OrareProMe.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte[]>("ExternalId")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrareProMe.Domain.Intention", b =>
                {
                    b.HasOne("OrareProMe.Domain.User", "Owner")
                        .WithMany("Intentions")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OrareProMe.Domain.Prayer", b =>
                {
                    b.HasOne("OrareProMe.Domain.Rosary", "Rosary")
                        .WithMany("Prayers")
                        .HasForeignKey("RosaryId");

                    b.Navigation("Rosary");
                });

            modelBuilder.Entity("OrareProMe.Domain.Rosary", b =>
                {
                    b.HasOne("OrareProMe.Domain.Intention", "Intention")
                        .WithMany("Rosaries")
                        .HasForeignKey("IntentionId");

                    b.Navigation("Intention");
                });

            modelBuilder.Entity("OrareProMe.Domain.Intention", b =>
                {
                    b.Navigation("Rosaries");
                });

            modelBuilder.Entity("OrareProMe.Domain.Rosary", b =>
                {
                    b.Navigation("Prayers");
                });

            modelBuilder.Entity("OrareProMe.Domain.User", b =>
                {
                    b.Navigation("Intentions");
                });
#pragma warning restore 612, 618
        }
    }
}
